### ISSUE TITLE
Swift 5.1.2 support

### ISSUE THREAD

**Issue by trevorwang** [phrase/ios-sdk#10]
It doesn't work when I updated to latest xcode. 

```
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: Pods/PhraseApp/PhraseApp.framework/Modules/PhraseApp.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

**Comment by winkelsdorf** [comment]
@trevorwang Thank you for bringing this to my attention. We will be releasing an updated framework later today which fixes module stability. Sorry for the inconvenience it caused you!

**Comment by angelolloqui** [comment]
Same thing here! waiting for that update! thanks!

**Comment by winkelsdorf** [comment]
An updated SDK that has been built for Swift 5.1.2 has been released: https://github.com/phrase/ios-sdk/releases/tag/1.2.2.

Due to a known issue with the Swift compiler itself, we need to postpone the use of Module Stability to a later release as this would would introduce a breaking change.

**Comment by angelolloqui** [comment]
Works fine! for future releases, I suggest you distribute the source code instead of the built framework. That way we could also contribute if anything arises. Thanks for the quick response anyway!

**Comment by winkelsdorf** [comment]
@angelolloqui Thank you for your feedback, you're welcome! We will discuss your suggestion internally 👍

**Comment by dmhts** [comment]
@winkelsdorf 
> Due to a known issue with the Swift compiler itself, we need to postpone the use of Module Stability to a later release

I'm just wondering, what known issue are you referring to?

**Comment by winkelsdorf** [comment]
@dmhts There is a known issue with the namespace of a framework and its classes, mentioned in the Xcode 11.2 release notes (https://developer.apple.com/documentation/xcode_release_notes/xcode_11_2_release_notes):

> If a module is built with BUILD_LIBRARIES_FOR_DISTRIBUTION and contains a public type with the same name as the module itself, clients will fail to import the module. (19481048) (FB5863238)

This has been reported in the Swift forums previously: https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962.

Despite this, there have also been reports that enabling `Module Stability` might lead to segmentation faults in the LLVM compiler. Source: https://forums.swift.org/t/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler/30431/7. 

We are currently investigating our options and evaluating the upcoming Xcode 11.2.1 release (currently in GM seed).

**Comment by dmhts** [comment]
Thanks, I thought you had some concrete issues with your library. Anyway, it's reasonable to wait until module stability gets stable 👍

**Comment by winkelsdorf** [comment]
@dmhts You're welcome and thank you for your understanding! No, just the compiler issue with the module's namespace. Exactly, we will test the new functionality with each release and provide `Module Stability` as soon as possible and as soon as it appears reasonable.

**Comment by winkelsdorf** [comment]
Update: A new release fully supporting module stability is available now. Please see https://github.com/phrase/ios-sdk/releases for details.

**Comment by dmhts** [comment]
@winkelsdorf Thanks a lot for letting us know!

**Comment by winkelsdorf** [comment]
@dmhts You're welcome!
