### ISSUE TITLE
Swizzling not working

### ISSUE THREAD

**Issue by irlennard** [phrase/ios-sdk#14]
I'm using the Phrase OTA SDK in my Swift app, and it appears that the swizzling is not working. `NSLocalizedString()` does not give me the updated translations, `Phrase.shared.localizedString(forKey:)` does however (I did not turn off swizzling). I'm using the latest SDK (2.1.0) with Xcode 11.4.1 and Swift 5.2.2.

**Comment by winkelsdorf** [comment]
@irlennard Thank you for your report!

When swizzling is enabled `Phrase.shared.localizedString(forKey:)` internally just forwards to `Bundle.main.localizedString(forKey:)` (as this method is swizzled).

Without seeing any code, I think you are probably running into a timing issue. The completion closure  of `updateTranslations()` is a safe place to re-assign translations with `NSLocalizedString()` or `Phrase.shared.localizedString(forKey:)`. Ensure dispatching to `mainQueue` first where needed.

Always a good hint: Please also try deleting the App from your Simulator or Device to see if the Bundle somehow got corrupted (not related to the OTA SDK).

Let me know if this helps.

**Comment by irlennard** [comment]
Thanks for the tip. It was indeed just a timing issue as I was initialising the Phrase SDK just after creating the app's root view controller.

**Comment by winkelsdorf** [comment]
@irlennard You're weclome, glad I could help! 😊 No problem, asynchronous network communication is always a bit tricky to handle, especially when UI comes into play.
