### ISSUE TITLE
Support manual app version entry

### ISSUE THREAD

**Issue by Alpexs** [phrase/ios-sdk#19]
Hello,

I saw that on Android the SDK supports a custom app version number ( `Phrase.setAppVersion("3.2.4");`), our app currently doesn't have a semantic version format ( we have something like `8304` ).
We do have a computed variable which returns the semantic formatted string.

Is it something that can/planned to get done on the iOS SDK ?

Thanks.

**Comment by winkelsdorf** [comment]
Hello @Alpexs,

thanks for the suggested enhancement! I will pass on the suggestion and think that we can already provide this in the next release.

Best regards,
Frederik

**Comment by winkelsdorf** [comment]
Hello @Alpexs,

I'm happy to announce a new release including your proposed change. Starting with Release 2.3.0 you can now provide an override with a semantic app version to the iOS SDK, too.

Release is available through CocoaPods or here: https://github.com/phrase/ios-sdk/releases/tag/2.3.0.

Best regards,
Frederik

Example given:
```swift
Phrase.shared.setup(
    distributionID: "your-ID",
    environmentSecret: "your-Secret",
    appVersionOverride: "1.4.0"
)
```
