### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by flashspys** [phrase/ios-sdk#2]
Do you have already an ETA for Swift 5 support?

**Comment by dmhts** [comment]
Up!

**Comment by theSoenke** [comment]
Hi, we have this on our roadmap. And we will likely create a new release for it soon. But I don't have an exact date for this yet

**Comment by ChristianSteffens** [comment]
Would be great to know a potential release date: This is currently blocking our project's migration to Swift-5.0. If you need any help testing the new release, we would be glad to help you out.

**Comment by theSoenke** [comment]
@ChristianSteffens Thanks for letting me know. Will definitely get back to you as soon as we have a release ready for testing

**Comment by dmhts** [comment]
@theSoenke Thanks, because this blocking our migration process as well.

**Comment by ANGOmarcello** [comment]
Would love to see this

**Comment by ChristianSteffens** [comment]
Seems to work - thanks a lot.

**Comment by theSoenke** [comment]
Great. Thanks for the confirmation
