### ISSUE TITLE
Better support for using PhraseSDK in extension (remove warning)

### ISSUE THREAD

**Issue by cheif** [phrase/ios-sdk#22]
Hi!

Right now it's possible to link against PhraseSDK from an extension, but you'll get the warning:
`ld: warning: linking against a dylib which is not safe for use in application extensions: .../PhraseSDK.framework/PhraseSDK`

I guess we're not unique in our desire for using OTA updates in extensions, and I hope that there's something you can do about it. 
In the best case it should just be to flick on `APPLICATION_EXTENSION_API_ONLY = YES;` in your build settings, but I realise that you might actually be using API:s that's not available in extensions.

**Comment by winkelsdorf** [comment]
Hi @cheif,

that's an excellent suggestion, thanks for bringing it to our attention!

You are right, we need to check API usage and for correct handling of Bundles and Network Sessions. I'll discuss this with the team and will keep you updated on this.

**Comment by winkelsdorf** [comment]
@cheif Just wanted to let you know, that the upcoming release will close this issue in a few days.

**Comment by cheif** [comment]
@winkelsdorf Looking forward to it! :)

**Comment by winkelsdorf** [comment]
@cheif New version is live. Looking forward to your feedback.

**Comment by cheif** [comment]
Now I've verified that we don't get the warning any more, great work @winkelsdorf !

**Comment by winkelsdorf** [comment]
@cheif Thank you very much for your kind words and the feedback, really appreciate that! 

Just a note, currently dSYMs shipped with the (xc)framework break the lldb debugger. See #30. We'll release a hotfix shorty, in the meantime you could simply delete the shipped dSYMs coming with the SDK.

**Comment by cheif** [comment]
Thank for the heads-up, I'll just hold of merging until 3.0.1 is out.

**Comment by winkelsdorf** [comment]
You're welcome! Yes, that's probably the best. Keeping you updated :)

**Comment by winkelsdorf** [comment]
@cheif v3.0.1 is out now. May take some time for CocoaPods to distribute the new Podspec (they have some issues the past 24 hrs).
