### ISSUE TITLE
Carthage build failed with Swift 5.3

### ISSUE THREAD

**Issue by aortegas** [phrase/ios-sdk#23]
*** Downloading binary-only framework PhraseSDK at "https://raw.githubusercontent.com/phrase/ios-sdk/master/PhraseSDK.json"

Incompatible Swift version - framework was built with 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53) and the local version is 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1).

**Comment by winkelsdorf** [comment]
@aortegas Please update your Carthage version to latest Carthage master. The Phrase SDK framework is built using Module Stability and works fine with Swift 5.3.

Please see https://github.com/phrase/ios-sdk/issues/13 and https://github.com/Carthage/Carthage/issues/2887.

Please let me know if this solves the issue for you.

**Comment by aortegas** [comment]
Resolved @winkelsdorf 
Thanks for your help.

**Comment by winkelsdorf** [comment]
@aortegas You're welcome, glad I could help!
