### ISSUE TITLE
Uses default language even though the list of preferred languages contains a valid language (that is not the default language)

### ISSUE THREAD

**Issue by mariaschmiterlow** [phrase/ios-sdk#27]
Hello Phrase!

**Summary:**
If the first item in the list of preferred languages is not supported by the app (or Phrase) it seems like Phrase OTA defaults to the default language even though the list contains languages that are supported (but is not the default language).

**Example:**
This example is taken from our app and please let me know if I have misunderstood something about the setup.

This is our configuration for our iOS project, i.e we support two languages "en-US" and "sv" where "en-US" is the default one.
<img width="277" alt="Skärmavbild 2021-01-20 kl  12 56 37" src="https://user-images.githubusercontent.com/15416618/105171906-1cc94b80-5b1f-11eb-815b-228d81bc0adf.png">
And the same goes for our Xcode project
<img width="512" alt="Skärmavbild 2021-01-20 kl  12 58 24" src="https://user-images.githubusercontent.com/15416618/105171972-38cced00-5b1f-11eb-803a-3fea6af3a6eb.png">
We have also configured the OTA configuration to fallback to language without region if necessary.
<img width="584" alt="Skärmavbild 2021-01-20 kl  12 59 13" src="https://user-images.githubusercontent.com/15416618/105172113-67e35e80-5b1f-11eb-9129-1776b24afc47.png">

This works perfectly fine if you have any of our two supported languages as the first supported language (here is an example where Swedish "sv-SE" is the preferred language and Norwegian is the secondary language). All strings coming from Phrase OTA is in Swedish.
![IMG_0045](https://user-images.githubusercontent.com/15416618/105179747-fa88fb00-5b29-11eb-92c4-d021cdea00f0.PNG)

But if you change the order in the example above (having Norwegian as first preferred language and Swedish as secondary) all strings coming from Phrase OTA are in English (default language).
![IMG_0041](https://user-images.githubusercontent.com/15416618/105179767-ffe64580-5b29-11eb-9d76-906d8e4912d9.PNG)

This is not aligned with the Apple's documentation on how this is handled in iOS (see this entry: https://developer.apple.com/library/archive/qa/qa1828/_index.html#//apple_ref/doc/uid/DTS40014938)
and it doesn't follow how the native UI components works.

This is an example from our app (when the user as Norwegian as first language and Swedish as second) where we use the native `ASAuthorizationAppleIDButton` for Apple sign in but custom `UIButtons` with localised string from Phrase OTA for the other two buttons.
The Apple button is handling the secondary language (Swedish that is) correctly but the translations from Phrase OTA gives us the default language English.

![IMG_0047](https://user-images.githubusercontent.com/15416618/105179273-6880f280-5b29-11eb-8c9e-e0d188fa82de.jpg)

To me it looks like that Phrase OTA only looks for the first preferred language and don't take the other languages into account at all.
Or have we missed anything in the configuration of our projects?

Thanks for your help!

**Comment by winkelsdorf** [comment]
Hello @mariaschmiterlow,

Thank you for the detailed report. Yes, that is correct - we use the first preferredLanguage. So, you are not missing anything out in your project's configuration. I have forwarded this to the team as a suggestion for improvement. There may also be similarities to ticket #17.

Unfortunately, I cannot make a statement about whether and how this feature can be implemented.

**Comment by mariaschmiterlow** [comment]
Thanks @winkelsdorf for your answer and confirming that nothing is wrong with our project setup!

I read through #17 and even though the issues are (probably) not the same they might contain similar touchpoint if/when fixed (but since I don't know your codebase that is ofc hard for me to answer).

Thanks anyway for forwarding it and answering my question! I'll keep an eye on the issue for the future.

**Comment by winkelsdorf** [comment]
You're welcome @mariaschmiterlow and sorry for the delay in responding to your query!

**Comment by winkelsdorf** [comment]
I welcome you to test this with our latest RC, where we adjusted the language detection logic: https://github.com/phrase/ios-sdk/releases/tag/4.0.1-rc.1

**Comment by winkelsdorf** [comment]
I am pleased to announce that v4.0.1 has just been released, which includes an improved language detection and fallback logic. I'm closing this ticket for now, if there are any questions about it, let us know - just reopen or create a new ticket.

**Comment by mariaschmiterlow** [comment]
Thanks @winkelsdorf for updating the issue and a RC to test out. We will look into it and hopefully it will solve the issue we saw previously 👍  Thanks again for getting back!

**Comment by winkelsdorf** [comment]
With pleasure @mariaschmiterlow! Among many other improvements, the new logic should cover exactly this use case, I look forward to your feedback.

**Comment by mariaschmiterlow** [comment]
Hi again @winkelsdorf 
We have now updated Phrase in our codebase and ensured that the issue ☝️ is actually fixed with the new release! Thanks a lot 🙏  And many thanks for keeping us in the loop!

And sorry for the late feedback! I had hopes to get this in much earlier but it wasn't possible 🙂
