### ISSUE TITLE
Misleading Package Reference Name 

### ISSUE THREAD

**Issue by tonnihyldgaard** [phrase/ios-sdk#32]
`/* XCRemoteSwiftPackageReference "ios-sdk" */,`

We have noticed that the Phrase SDK for iOS is named `ios-sdk` in the `XCRemoteSwiftPackageReference`, this could potentially lead to package conflicts if another framework uses the same name for their SDK. 

It's a minor thing, but I suggest changing the reference name to reduce risk of conflicts :)

**Comment by winkelsdorf** [comment]
Hello @tonnihyldgaard,

yes, excellent catch, we already noticed the same!

Sadly as of now there is no way to override the Package Reference Name Xcode picks as to my knowledge. If you look at our Package file, we already set the Package Name to `PhraseSDK` accordingly (in https://github.com/phrase/ios-sdk/blob/master/Package.swift) but Xcode uses the Repository Name as Reference Name.

From what I know the internal Package resolution is tied to the Repository, so beside this misleading display name no conflicts should occur, even if another Repo is named `ios-sdk`, too.

hth!

- Frederik

**Comment by winkelsdorf** [comment]
@tonnihyldgaard Without any change to our Package, starting with Xcode 12.5 this seems to work correctly:

<img width="264" alt="Screen Shot 2021-05-27 at 09 11 38" src="https://user-images.githubusercontent.com/1413291/119781920-dc624b80-becb-11eb-93ed-eafcc76b37e2.png">

<img width="852" alt="Screen Shot 2021-05-27 at 09 11 23" src="https://user-images.githubusercontent.com/1413291/119781939-e1bf9600-becb-11eb-9d06-93c3380c245b.png">

Xcode now takes not only the Repo url into account but correctly displays the Package name from the Package manifest.

Let me know if this works for you now, too. Going to close this issue soon.
