### ISSUE TITLE
Planning for OTA SwiftUI support?

### ISSUE THREAD

**Issue by bill-florio** [phrase/ios-sdk#44]
Hi! I would like to ask it there any planning to support SwiftUI? Currently I have a workaround like this:
```
    let text: LocalizedStringKey?
    let string: String?

   @ViewBuilder
     private var sharedText: some View {
         if let text = text {
             Text(text)
         } else if let string = string {
             Text(string)
         } else {
             Text("")
         }
     }
``` 

But my App have hundreds of Texts and Buttons to change and it is not practical.

**Comment by bill-florio** [comment]
Thanks for your detailed answer. There will be quite a lots of Text/Button and etc in my project already using LocalizedKey.

**Comment by winkelsdorf** [comment]
You are welcome! I can understand that this is not a very satisfactory answer, unfortunately. If this changes, we will of course be happy to inform you.
