### ISSUE TITLE
New strings values are not available on updateTranslation completion handler

### ISSUE THREAD

**Issue by h-leroy-betclic** [phrase/ios-sdk#51]
New strings values are not available on updateTranslation completion handler

On PhraseSDK 4.0.1 (spm install) when calling Phrase.shared.updateTranslation or Phrase.shared.updateTranslation(for:), the strings that have been synchronised can't be retrieve in the completion handler.

Scenario (run on simulator iOS 16.1 - OTA release are in development status):
- The app is already installed and have sync with an OTA release A.
- I make changes and create an OTA release B.
- I launch the app.

I use an HTTP proxy that confirm the sync is done with new strings value.
I start the sync before func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) end.
=> I expect to use the new value in the completion handler as the documentation is telling it (may be it is a regression).

I use the following to retrieve the strings value :
- Phrase.shared.localizedString(forKey: <key>, table: <the table i used in my app>)
- Phrase.shared.localizedString(forKey: <key>, table: nil)
- Phrase.shared.localizedString(forKey: <key>, table: "Localizable")
- NSLocalizedString(<key>, tableName: <the table i used in my app>, bundle: Bundle.main, comment: "")
- NSLocalizedString(<key>, tableName: nil, bundle: Bundle.main, comment: "")
- NSLocalizedString(<key>, tableName: "Localizable", bundle: Bundle.main, comment: "")

None of these give the right value.
BUT on the next launch, the string values are the last synchronised values.

**Comment by h-leroy-betclic** [comment]
Even i reload view controller, i will get the same old values : if it's not ok in the completion handler, it still will not be ok a step further in the view controller, that is calling the exact same function (NSLocalizedString).
It's a bug/regression in your sdk.

The feature you sell is to refresh strings between appstore delivery. Imagine i create an OTA release :
- my users will receive the new strings on next launch (an app can live in memory during several days ≈ 3 days)
- the new strings will be **available** on the next launch (again ≈ 3 days) !!!

It's just not possible to an OTA solution to be longer than an appstore delivery... the second case should not exist.

**Comment by winkelsdorf** [comment]
@h-leroy-betclic Thank you for your message and the issue report.

I was able to reproduce your issue, it is related to iOS caching the content of the already existing Bundle. The new content is not reloaded, even after the files have changed.

We are investigating a way around this limitation. Keeping you updated here.

**Comment by h-leroy-betclic** [comment]
Hi @winkelsdorf ,
Thank you for fixing the issue.
When do you plan to release a new version of the sdk ?

**Comment by winkelsdorf** [comment]
Hi @h-leroy-betclic,

sorry for closing this ticket automatically by referencing it from our prepared release. The release is upcoming within the next hours.

hth!

**Comment by h-leroy-betclic** [comment]
Hello @winkelsdorf,
Can you merge the PR https://github.com/phrase/ios-sdk/pull/52 ?
Thank's

**Comment by winkelsdorf** [comment]
Hello @h-leroy-betclic,

I am currently waiting for the approval. Sorry for the delay and inconvenience but the release will be available asap.

**Comment by winkelsdorf** [comment]
@h-leroy-betclic Release 4.1.0 has just been published. Please check if your problem has been solved and thank you again for your patience!

**Comment by h-leroy-betclic** [comment]
@winkelsdorf Thank's it seems ok

**Comment by winkelsdorf** [comment]
@h-leroy-betclic Glad to hear that and thank you for your feedback! Closing this issue now 🎉
