### ISSUE TITLE
Can we get a new "Example App"

### ISSUE THREAD

**Issue by oezguercelebi** [phrase/ios-sdk#53]
The current demo app is 6 years old and I noticed that Android has an example app that is regularly updated https://github.com/phrase/android-sdk-example. It would be nice to have a new one for iOS.

I have tried to implement Phrase SDK with OTA. But I am doing something wrong and it is not working. I have already contacted support about it.

Just want to make sure that the Phrase SDK integration is correct from my side and it is something else.

**Comment by theSoenke** [comment]
Hi @oezguercelebi, that's a good point and I'll have a look whether we can provide an up to date example with the over-air-sdk

**Comment by theSoenke** [comment]
We had a conversation about a new example app and are working on an entirely new demo application. The new demo app should include demos for UIKit and SwiftUI. I'll share it here once it is available.

**Comment by theSoenke** [comment]
Hey @oezguercelebi, our iOS demo app is now public at https://github.com/phrase/ios-demo-app Hope this already helps with the implementation
