### ISSUE TITLE
Configure OTA with two different distributions

### ISSUE THREAD

**Issue by JAIRMG** [phrase/ios-sdk#58]
Hi, I would like to update strings that live in two different projects. However, distributions only accept one project. If this is not possible, can I configure the project twice in the app using different distributions?

thanks!

e.g. 

```
// 1st distribution 
Phrase.shared.setup(distributionID: "xx",
                        environmentSecret: "xx")
                        
 Phrase.shared.updateTranslation()
 
 and immediately
 
 // 2nd distribution 
Phrase.shared.setup(distributionID: "yy",
                        environmentSecret: "yy")
                        
 Phrase.shared.updateTranslation()
```

**Comment by JAIRMG** [comment]
Actually I jus tested the example provided in my comment above and if I try to setup a second time then the strings from the first distribution stop working 🙁

**Comment by theSoenke** [comment]
Hi @JAIRMG, unfortunately distributions can currently only be connected to one project and only one distribution can be used at a time by the SDK. We had a couple similar features requests and are looking into it how we can support multiple projects better in the SDK. But for now the solution would be to have one project containing all needed keys

**Comment by JAIRMG** [comment]
Oh, understood, thanks for the quick response. Have a nice day
