### ISSUE TITLE
Support mac catalyst

### ISSUE THREAD

**Issue by taimur** [phrase/ios-sdk#60]
Please modify the sdk to support mac catalyst. Thank you :)

**Comment by winkelsdorf** [comment]
@taimur: Thanks for the suggestion, we will discuss this internally and do some tests.

**Comment by winkelsdorf** [comment]
I am happy to announce that we are likely to release Mac Catalyst support with the upcoming version 4.3.0 🎉

**Comment by winkelsdorf** [comment]
Released with 4.3.0
