### ISSUE TITLE
Malformed Archive Error and SPM Compatibility Issue

### ISSUE THREAD

**Issue by oznurAkgun** [phrase/ios-sdk#63]
While attempting to utilize this SDK via SPM, I faced the following error:

**error: archive at path '/Users/core/.jenkins/workspace/iOS/build/InHouse/Galaxy.xcarchive' is malformed**

Upon inspecting the contents of the 'xcarchive' folder, I discovered that there was no 'info.plist' file present.

<img width="758" alt="Screenshot 2023-09-13 at 13 09 56" src="https://github.com/phrase/ios-sdk/assets/8256954/291611e8-3760-45fc-9f52-85d584dca1bc">

Later, according the my search I found that in some cases BCSymbolMaps and dSYMs caused this error. I installed the xcframework and deleted those files, it worked successfully

![screenshot_2023-09-11_at_15 15 41_720](https://github.com/phrase/ios-sdk/assets/8256954/d50ee4cb-680d-405d-a99f-b8308120de7c)

However, now we can't use SPM. Could you publish a new release without these files?

source: https://stackoverflow.com/a/68780570

**Comment by carstenapploft** [comment]
Hi @oznurAkgun,

I will look into the problem.

A little context as to why dsym files are supplied at all: https://github.com/phrase/ios-sdk/issues/38
Therefore, I would try to keep them for now.

I have already tried to recreate the problem, but so far without success.

To look at the problem in more detail, I need some information:

Which Xcode version are you using?

Have you ever integrated the SDK with another dependency manager and did that work?

It would be helpful if you could provide an example project where you have the problem. Remember to remove all sensitive information and logic.

**Comment by oznurAkgun** [comment]
Hi @carstenapploft 
Seems I can't provide you with the example project since I faced this problem during our enterprise release process. it builds successfully on local, but doesn't on Jenkins
I haven't tried other dependency managers as we use SPM in this project
Xcode version:  14.3.1

**Comment by carstenapploft** [comment]
Hi @oznurAkgun ,
thanks for the information. 

I took another look at our script for generating the xframework and bitcode is still enabled there. Bitcode is no longer supported since xcode 14. As soon as we remove bitcode support, the BCSymbolMaps should also disappear. According to your stackoverflow link, this should possibly solve your problem. We are planning small updates for the next 1-2 weeks. I will talk to my team about removing bitcode and let you know when we have a new version.

**Comment by carstenapploft** [comment]
Hi @oznurAkgun ,
we have now released version 4.3.1. The release is now without bitcode.
I hope the problem is now solved.
