### ISSUE TITLE
Add Privacy Manifest file to library if needed

### ISSUE THREAD

**Issue by jayeshkawli** [phrase/ios-sdk#69]
Hello,

I am a current user of your ios SDK. I have a question about the Privacy Manifest.

At WWDC23 Apple is requiring all api calls that fall under this ruleset 

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

be added to a privacy manifest file.
Does Phrase's iOS SDK need to include this manifest?
Please let me know about your upcoming plans to apply the privacy manifest.

Thank you!!!

**Comment by carstenapploft** [comment]
Hi @jayeshkawli ,

we will make a release with the privacy manifest in the near future.
I will get back to you as soon as we have released it.

**Comment by jayeshkawli** [comment]
> Hi @jayeshkawli ,
> 
> we will make a release with the privacy manifest in the near future. I will get back to you as soon as we have released it.

Thank you @carstenapploft . Do you know if the privacy manifest is actually mandatory for Phrase SDK?

**Comment by carstenapploft** [comment]
In my opinion, a privacy manifest is not mandatory for Phrase SDK. 
The SDK is not explicitly mentioned by Apple:
https://developer.apple.com/support/third-party-SDK-requirements/

But we add it because we use the UserDefaults.

**Comment by carstenapploft** [comment]
@jayeshkawli a new release with privacy manifest is now available:
https://github.com/phrase/ios-sdk/releases/tag/4.4.1

**Comment by jayeshkawli** [comment]
Thank you for the quick turnaround. Much appreciated
