### ISSUE TITLE
Phrase OTA cache issue

### ISSUE THREAD

**Issue by CatalinNDKV** [phrase/ios-sdk#79]
Hi team,

I integrated Phrase OTA and the values are not cache. Every time I open the application Phrase OTA is fetching the new translations and the values are not cache and because of that the application still using the old translation that are in the Localizable file. I have opened the application multiple times.

Do you have any suggestions/idea how to fix this issue?

**Comment by carstenapploft** [comment]
Hi @CatalinNDKV,

can you check if the SDK gives you an error(or a success)?
You can use the code from our demo app function ‘[updateTranslations](https://github.com/phrase/ios-demo-app/blob/main/Example/AppDelegate.swift)’. 
Can you confirm that you are using the current SDK version (4.4.1)?

**Comment by CatalinNDKV** [comment]
Hello,

I checked and the SDK doesn't give me any error. When I use updateTranslations it is successful but the translation is not available when opening the second time the application. I am using version 4.4.1 and I have used the code from the demo app for updateTranslations.

**Comment by theSoenke** [comment]
Should be resolved now. Please leave a comment if there's still anything that's not working
