### ISSUE TITLE
Swift 5.1 support

### ISSUE THREAD

**Issue by flashspys** [phrase/ios-sdk#8]
As in #2, Swift 5.1 should be supported, too.

**Comment by theSoenke** [comment]
Hi, we plan to release soon an updated version for Swift 5.1. We will let you know as soon as it is available

**Comment by jdmoreira** [comment]
I upvote this request

**Comment by ChristianSteffens** [comment]
Any news on that - PhraseApp's SDK is the only framework holding our Swift-5.0 migration back.

**Comment by theSoenke** [comment]
We are currently waiting for the final 5.1 release of Swift before we update the SDK. Any reasons why you are already using the pre-release version of Swift?

**Comment by flashspys** [comment]
We are testing our app already on iOS 13 to be ready for the launch in September. For this we already migrated our codebase to be compatible with Swift 5.1. You are the only binary Swift SDK we are using at the moment. For every minor Swift update we have to first exclude your SDK and then, if you released your update, we include it again. And exactly this is the reason why you don't release a **binary** Swift framework, prior to module stability, introduced in Swift 5.1. If you absolutely want to publish a binary Swift SDK and keep the source code, you are in the responsibility to update your SDK faster than we update our codebase.

**Comment by timleers** [comment]
@flashspys you are absolutely right. We will take care of this issue with high priority and inform you as soon as the new version is released which will probably happen within the next two days

**Comment by timleers** [comment]
@flashspys new version 1.2.0 was generated with Swift version 5.1 (swiftlang-1100.0.212.5 clang-1100.0.28.2) and is available now
Please let us know if you have any issues with it

**Comment by ChristianSteffens** [comment]
You should probably release this version as beta release - otherwise all non Swift `5.1` users will have a problem now ;-)

**Comment by timleers** [comment]
@ChristianSteffens good point :) I changed that and sorry for the inconvenience

**Comment by theSoenke** [comment]
Hi, a quick update regarding Swift 5.1 support. As @ChristianSteffens pointed out correctly this still is an issue for all non Swift 5.1 users. For now, the master now points again at the last release for Swift 5.0. To be able to use use the Swift 5.1 version you can add the following to your Podfile: `pod 'PhraseApp', :git => 'https://github.com/phrase/ios-sdk.git', :tag => '1.2.0-beta'
`

**Comment by jensutbult** [comment]
There's still no functional SDK that work with the latest version of Xcode. We really need this and I guess a lot of other customers do as well. Since we pay handsomely for the Phraseapp service I don't think it is unreasonable to expect a matching SDK well ahead of the launch a new version of iOS.

**Comment by theSoenke** [comment]
Hi, we are currently working on a solution to provide support for the latest XCode version. Unfortunately there are some breaking changes and not all tools are fully ready yet. We will provide further details about this on Monday. We will also make sure that we have a smoother upgrade experience for releases in the future whenever possible

**Comment by suho** [comment]
Hi @theSoenke, do you have any update support for the latest Xcode version?. 
I'm working on Xcode 11.0, and I have this error:
`Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Pods/PhraseApp/PhraseApp.framework/Modules/PhraseApp.swiftmodule/x86_64.swiftmodule`

**Comment by theSoenke** [comment]
Quick update. With the final releases of Swift 5.1 and XCode 11 we will publish a new release as soon as possible

**Comment by suho** [comment]
Thanks

**Comment by ValentinDenis** [comment]
Hello @TheSoenke, any update on the new version ? Can you provide an ETA ? We had to downgrade to XCode 10.3 just for one project that uses the Phrase SDK

**Comment by winkelsdorf** [comment]
@ValentinDenis The release of the updated Phrase SDK is planned for the next 24 hours

**Comment by winkelsdorf** [comment]
The Swift 5.1 compatible Phrase SDK release has been published. Feel free to update using `pod update` if you're using CocoaPods. Let me know if you have any further questions.

**Comment by jensutbult** [comment]
Are you guys sure 1.2 is compiled with Swift 5.1? I get the following error message when compiling:
`Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler`
The header file (PhraseApp-Swift.h) also seems to indicate that 1.2 is in fact built with Swift 5.0:
`// Generated by Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)`

**Comment by winkelsdorf** [comment]
@jensutbult Yes, Swift 5.1 had been used.

I re-downloaded it and in the `PhraseApp-Swift.h` I see the correct comment:
<img width="692" alt="Screenshot 2019-09-27 at 15 50 03" src="https://user-images.githubusercontent.com/1413291/65774554-c45a8780-e13e-11e9-82ca-ff665b76123c.png">

Can you please verify that you updated your Pod or download the framework from https://github.com/phrase/ios-sdk/releases/download/1.2.0/PhraseApp.zip?

**Comment by winkelsdorf** [comment]
@jensutbult Issue has been resolved. Please force a re-download of the framework.

I assume you are using CocoaPods? If so, please remove the PhraseApp SDK from it's cache and update the pod by running:

```shell
pod cache clean PhraseApp 
pod update
```

Sorry for the inconvenience this has created for you!
